# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://ux-o.github.io/zyx/"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"

    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "about"
    name       = "About"
    url        = "https://ux-o.github.io/zyx/p/about/index.md"

    [social.params]
        icon = "brand-github"
